# Generated by Django 5.0.1 on 2024-01-28 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('QuerySet_App', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='pass_marks',
        ),
    ]
