# Generated by Django 5.0.1 on 2024-01-29 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuerySet_App', '0004_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='subject',
            field=models.CharField(max_length=40),
        ),
    ]
